### ISSUE TITLE
Not working when there are Umlauts in the Output

### ISSUE THREAD

**Issue by SenorCerveza** [rodneyviana/ODSyncUtil#10]
Hello

We are using a German environment to query the OneDrive Status. As soon the Field "Label" contains a string with an Umlaut (ä, ö, ü), the Output stops at this point resulting in an incomplete JSON response in STDOUT.

We tried to run the binary in the 25001 Codepage (UTF8) and also redirecting the output directly to a file with UTF8 and also changed the system wide Regional Settings to the new UTF8 (beta) feature on the Operating System.

None of these worked. Can this please be addressed? As I can see, the JSON serializer using UTF16 which should be fine but it seems somehow the API class can't handle non latin chars.

Kindly

**Comment by rodneyviana** [comment]
SenorCerveza (finally a worth alias :) ),

See the new version I just published and follow the Troubleshooting steps in README,md and report the results if you still have problems.

**Comment by rodneyviana** [comment]
Also I made changes to allow -d to work with -s (version 1.0.4.5000)

**Comment by SenorCerveza** [comment]
Allright thanks! Looks promising so far.
We implemented it as additional step but not relying on it on productive environment. So we see if it "would" fail.

Will report back.

And thanks :)

**Comment by SenorCerveza** [comment]
Hey

It seems it working now. We hadn't a single issue with using the file output and reading it back with Powershell.
Thanks a lot :)


Kindly
