### ISSUE TITLE
No description on Outputs

### ISSUE THREAD

**Issue by dillon-LACT** [rodneyviana/ODSyncUtil#11]
Trying to find the iconURI file you indicated would outline what each code means, not finding that

**Comment by aakash-shah** [comment]
Thanks for the providing the file names! I'm not the OP, but could you provide what number from "CurrentState" corresponds to each of the files you've listed above? So for instance you've indicated in the readme file that:
0 = "CloudIconSynced"

Could you also provide the expected numbers for the other states listed above?

Thanks!

**Comment by rodneyviana** [comment]
I don’t have the information, thus the hack with file names. If you find the association after using long enough, please post here so others can benefit.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aakash-shah** [comment]
Ahh ok I'll try to post information if I find it. Thanks!

**Comment by aakash-shah** [comment]
Here is what I have so far:

| CurrentState | Label | IconUri |
| -------- | ------- | ------- |
| 0 | OneDrive | CloudIconSynced.svg |
| 1 | Syncing | CloudIconSyncing.svg |
| 2 | Paused | CloudIconPaused.svg |
| 3 | Error | CloudIconError.svg |
| 5 | Offline | CloudIconOffline.svg |

I haven't been able to test for Warning yet, but I would assume it is 4

**Comment by rodneyviana** [comment]
That’s great. I will update README.md and probably add the state names to the results. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dillon-LACT** [comment]
AMAZING THANK YOU GUYS!!!

**Comment by dillon-LACT** [comment]
Amazing, thank you!


[Logo, company name  Description automatically generated]





Dillon Daniel

Helpdesk / Automation Engineer



P.  424.226.1688 Ext.114


Book a meeting with me: https://usemotion.com/meet/dillond/meeting


370 Amapola Ave., Suite 201

Torrance, CA 90501



www<http://www.logictcg.com/>.logictcg.<http://www.logictcg.com/>com<http://www.logictcg.com/>



By doing great work, we empower organizations and communities to make a bigger impact for those they serve.



think great > be great > do great!

(Click here to learn more about our core values)<https://logictcg.com/our-values/>





CONFIDENTIALITY NOTICE: This e-mail message and any attachments are intended solely for the use of the intended recipient and may contain information that is confidential, privileged, and exempt from disclosure under applicable law. If you are not the intended recipient, you are not permitted to read, disclose, reproduce, distribute, use or take any action in reliance upon this message and any attachments, and we request that you promptly notify the sender and immediately delete this message and any attachments as well as any copies thereof. Delivery of this message to an unintended recipient is not intended to waive any right or privilege.

________________________________
