### ISSUE TITLE
Additional Details From ODSyncUtil

### ISSUE THREAD

**Issue by aakash-shah** [rodneyviana/ODSyncUtil#14]
Hello! I have a few team sites connected to my primary OD4B account, and I have 2-3 separate OD4B accounts on separate tenants. Since there is more than 1 account/site, it is difficult to determine which returned object corresponds to which folder path/site.

While looking further into the returned SyncRootId I found some related information at 2 locations:

The key below appears to reveal both the folder path, the SPO URL, and also appears to indicate whether it's the primary site or a Team Site. 
HKEY_CURRENT_USER\Software\SyncEngines\Providers\OneDrive

I found another key, which corresponds to the SyncRootId, although it appears to have fewer useful attributes (from what I can tell) at this location:
HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\SyncRootManager

I wasn't sure if your code perhaps references either of these registry locations. Do you have any plans to include this additional information in the output of ODSyncUtil.exe or perhaps Get-ODStatus.ps1?

Thanks!

**Comment by aakash-shah** [comment]
FYI I added some PowerShell code on a local copy of Get-ODStatus.ps1 to help extract information from these 2 registry locations. If you would be interested, let me know and I'll try to figure out how to contribute this in GitHub. I recognize this would split the extraction functionality from the exe file though since the rest of the logic is in there.

**Comment by aakash-shah** [comment]
Sounds good, thanks!

**Comment by rodneyviana** [comment]
The initial request plus the status string (I could find the exact names in the API enum).
Those latest fields are not so universal as you think, but I believe UrlNamespace is useful but I will not implement now as it requires matching the OneDrive type to the key.

**Comment by aakash-shah** [comment]
Ok thanks. I can add the additional information on my end if I need - appreciate your help with this!
