### ISSUE TITLE
Necessity of 32-bit bundle

### ISSUE THREAD

**Issue by Datto-StanLee** [rodneyviana/ODSyncUtil#18]
Hi, I'd like to make sure I understand this properly before I commit to anything.

The binary is available for Windows 10 and Windows 11, but Windows 10 support relies on a DLL which is 64-bit only.
Windows 11, meanwhile, is only available in 64-bit architecture.

As such, the only possible use case where ODSyncUtil should be needed in 32-bit architecture is on Windows 11 systems where the 32-bit version of OneDrive is installed, but [OneDrive automatically updates to the 64-bit version on Windows 11](https://uk.pcmag.com/onlinecloud-backup-services/133308/microsoft-is-silently-upgrading-your-onedrive-installation-to-64-bit).

So – what use case is there for the 32-bit binary?

**Comment by rodneyviana** [comment]
> Hi, I'd like to make sure I understand this properly before I commit to anything.
> 
> 
> 
> The binary is available for Windows 10 and Windows 11, but Windows 10 support relies on a DLL which is 64-bit only.
> 
> Windows 11, meanwhile, is only available in 64-bit architecture.
> 
> 
> 
> As such, the only possible use case where ODSyncUtil should be needed in 32-bit architecture is on Windows 11 systems where the 32-bit version of OneDrive is installed, but [OneDrive automatically updates to the 64-bit version on Windows 11](https://uk.pcmag.com/onlinecloud-backup-services/133308/microsoft-is-silently-upgrading-your-onedrive-installation-to-64-bit).
> 
> 
> 
> So – what use case is there for the 32-bit binary?

I tried to create a stub for 32-bit but it won't compile. I am sorry for that.
