### ISSUE TITLE
Issue with ODSyncUtil returning zero information.

### ISSUE THREAD

**Issue by DIT-Matthew** [rodneyviana/ODSyncUtil#20]
We are using this tool with Datto RMM and they advised i should open a ticket here.  We are receiving alerts with a subject of Error.  When Datto RMM has looked into this for us they stated the below.  We are happy with the product as it does work well but we are getting a lot of error alerts which have no data in them.  Datto RMM initially thought it was due to one drive not being configured but that is not the case.  

Hello Matthew,
 
All three accounts have zero information on them. Notice how none of them have a "currentstatestring" or "isquotaavailable" value – these are things we can use to gather whether ODSyncUtil is actually getting information from onedrive. 
 
So, ODSyncUtil is at fault because it can't get any information. You caN to file an issue ticket at [https://github.com/rodneyviana/ODSyncUtil/](https://shared.outlook.inky.com/link?domain=github.com&t=h.eJxNjrEOgjAURX-FdDYtLYQCE4O7g_EDCu8JDVBI-8Cg8d-1G-vJuSf3wzY_sTphA9EaaiF6S8PW8m6ZhV_A4bFb44y4Xe-H6x5kJ8EuCRvjBOyOvkdHlsRsiAZ8NSfGHZKQKm-fBZgcMomqKFQqAUpsq8ykf1wJqaXWpU6V5mkV0xjTYVvXxVMzmoCH4W90gGGMr6ICUTmz7w_g5EB9.MEUCICkswzPwn7R3PdLRjaNgnR_ctM7sxMmXy7WWhsxe0-pZAiEAvx70GDYAkqjj7n2Zoruj6-Iput03hZmtJMoRwRTtKt4) but we're doing all we can.

**Comment by Datto-Kris** [comment]
I worked with Matthew internally and found this was mostly related to a Non-Admin Windows User being logged-in which cannot properly register a DLL file (limitation with regsvr32 command in Windows OS). Once the "OneDriveFlyoutPS.dll" was successfully registered as Local SYSTEM User in a script then ODSyncUtil ran as the logged-in user, it fixed the data output issue from ODSyncUtil.

**Comment by rodneyviana** [comment]
> I worked with Matthew internally and found this was mostly related to a Non-Admin Windows User being logged-in which cannot properly register a DLL file (limitation with regsvr32 command in Windows OS). Once the "OneDriveFlyoutPS.dll" was successfully registered as Local SYSTEM User in a script then ODSyncUtil ran as the logged-in user, it fixed the data output issue from ODSyncUtil.

Thank you for taking care of this, I couldn't work on my open source projects lately.
