### ISSUE TITLE
Can't check a particular folder or file status

### ISSUE THREAD

**Issue by LordHumphrey** [rodneyviana/ODSyncUtil#8]
In your [ODSyncService](https://github.com/rodneyviana/ODSyncService), I can check a particular folder or file status using `-ByPath`.
But I can’t do it like that for this project.
I am not an English native speaker, my text may puzzle you, I am sorry.
Thank you. God bless you.

**Comment by rodneyviana** [comment]
Hi LordHumphrey,

I can understand you well, no need to apologize. This version is a new one that DOES NOT include ```-ByPath```
You can still use this version that includes ```-ByPath``` https://github.com/rodneyviana/ODSyncService

**Comment by mwalter027** [comment]
Hey Rodney,

I need also this functionality - but Running on W11. Did you plan to bring up a new Version from the dll?

**Comment by rodneyviana** [comment]
This functionality from previous version should work in Windows 11.

**Comment by rodneyviana** [comment]
Using the new API is not possible to get -ByPath but previous version (https://github.com/rodneyviana/ODSyncService) should work in Win11, the rest will not work in Win11.
